
#GATEWAY'S CONFIG
server:
  port: 0

spring:
  application:
    name: notifications
  datasource:
    url: jdbc:postgresql://revpracticedb.chqf3b3u3aqm.us-east-2.rds.amazonaws.com/p3link
    username: ${LINK_NOTIFICATIONS_DB_USERNAME}
    password: ${LINK_NOTIFICATIONS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

#hibernate:
#  dialect: org.hibernate.dialect.PostgresSQL82Dialect
#  hbm2ddl:
#    auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id:  ${spring.application.name}:${random.value}
